version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: siragu
      POSTGRES_PASSWORD: siragupassword
      POSTGRES_DB: siragu_trace
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
